import type { PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import NextLink from 'next/link'
import { Noto_Sans_JP } from 'next/font/google'
import styles from './layout.module.css'
import "./globals.css"

const inter = Noto_Sans_JP({
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Next.js with MDX content",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <main className={styles.main}>
          <header className={styles.header}>
            <h1 className={styles.headerTitle}>
              <NextLink href="/">Next.js with MDX content</NextLink>
            </h1>
            <nav className={styles.nav}>
              <NextLink href="/post">Post</NextLink>
              <NextLink href="/categories">Categories</NextLink>
              <NextLink href="/author">Author</NextLink>
            </nav>
          </header>
          <div className={styles.content}>
            {children}
          </div>
          <footer className={styles.footer}>
            <p>Next.js with MDX content</p>
          </footer>
        </main>
      </body>
    </html>
  )
}